# NumPy Assignment

## Import the numpy package under the name as np & print the numpy version

In [59]:
import numpy as np

np.__version__

'1.22.4'

## Create a null vector of size 10

In [60]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create a null vector of size 10 but the fifth value which is 1

In [61]:
null_vector = np.zeros(11)
null_vector[5] = 1
null_vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Create a vector with values ranging from 10 to 49

In [62]:
vector = np.arange(10, 50)

vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Reverse a vector (first element becomes last)

In [63]:
vector = np.array([1, 2, 3, 4, 5])
ters_vector = np.flip(vector)
ters_vector


array([5, 4, 3, 2, 1])

## Create a 3x3 matrix with values ranging from 0 to 8

In [64]:
matrix = np.arange(9).reshape((3, 3))
matrix


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Find indices of non­zero elements from [1,2,0,0,4,0]

In [65]:
arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)
nonzero_indices[0]

array([0, 1, 4])

## Create a 3x3 identity matrix
Identity matrix, kare matrisler için özel bir türdür. Diagonalindeki tüm elemanlar 1, diğer elemanlar ise 0 olan kare matrisdir.

In [66]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Create a 3x3x3 array with random values

---



In [67]:
random_array = np.random.rand(3, 3, 3)
random_array

array([[[0.60774196, 0.77134045, 0.83851087],
        [0.34362024, 0.90788172, 0.46855583],
        [0.22244635, 0.917335  , 0.1628757 ]],

       [[0.07550715, 0.077679  , 0.73317963],
        [0.94075598, 0.50065979, 0.98029448],
        [0.63467703, 0.38583593, 0.79761064]],

       [[0.13782551, 0.45507718, 0.54238122],
        [0.92125778, 0.15652822, 0.7864987 ],
        [0.39329412, 0.84930138, 0.95954867]]])

## Create a 10x10 array with random values and find the minimum and maximum values

In [68]:
random_array = np.random.rand(10, 10)
random_array

array([[0.71891462, 0.19429896, 0.78086122, 0.79332576, 0.79603806,
        0.39078625, 0.7962984 , 0.7210208 , 0.28075541, 0.95565184],
       [0.30546354, 0.2737673 , 0.78722062, 0.63881877, 0.49090951,
        0.04288245, 0.97779081, 0.08436689, 0.92849984, 0.4560372 ],
       [0.75946611, 0.19098863, 0.20359207, 0.95026856, 0.87365014,
        0.47463875, 0.747064  , 0.54683911, 0.51708304, 0.01483618],
       [0.95427264, 0.76987303, 0.64326893, 0.18179501, 0.12485485,
        0.02325742, 0.72180599, 0.75548639, 0.43110112, 0.98096722],
       [0.55836176, 0.68925429, 0.11754638, 0.07947748, 0.01382007,
        0.57212973, 0.03899546, 0.51604246, 0.10472665, 0.37631198],
       [0.20980956, 0.81214836, 0.86464038, 0.53660787, 0.52841103,
        0.15755613, 0.61899435, 0.45729695, 0.25970167, 0.96614209],
       [0.05744605, 0.67520868, 0.10125785, 0.04640832, 0.53816191,
        0.0122516 , 0.82701642, 0.94537709, 0.19118694, 0.12477604],
       [0.44690533, 0.53593496, 0.8633395

## Create a random vector of size 30 and find the mean value

In [69]:
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)

print(random_vector)
print("Ortalama Değer:", mean_value)

[0.23744498 0.26639992 0.53025673 0.08718927 0.3594451  0.66309087
 0.76178906 0.16838283 0.26220204 0.59066514 0.98213846 0.77863613
 0.35613498 0.12453987 0.24686964 0.58647827 0.53392957 0.22388041
 0.30556995 0.79438757 0.89283871 0.6910811  0.04793289 0.62060076
 0.58767836 0.97714172 0.5171187  0.00809802 0.06680248 0.64641318]
Ortalama Değer: 0.46383789123587355


## Create a 2d array with 1 on the border and 0 inside

In [70]:
arr = np.zeros((5, 5))

arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [71]:
arr = np.zeros((5, 5))

np.fill_diagonal(arr[1:], np.arange(1, 5))

arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

## Create a 8x8 matrix and fill it with a checkerboard pattern

In [72]:
matrix = np.zeros((8,8),dtype=int)

matrix[1::2,::2] = 1
matrix[::2,1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Create a checkerboard 8x8 matrix using the tile function

In [73]:
sub_matrix = np.array([[1, 0], [0, 1]])

matrix = np.tile(sub_matrix, (4, 4))

print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [74]:
arr = np.random.rand(6, 7, 8)

index_100 = np.unravel_index(100, arr.shape)

print("Index of 100th element: ", index_100)

Index of 100th element:  (1, 5, 4)


## How can I create an array with dimensions (6, 7, 8) using arange, and find its last element?

In [75]:
arr = np.arange(6*7*8).reshape((6, 7, 8))

last_element = arr[-1, -1, -1]

print("Last element of the array:", last_element)

Last element of the array: 335


## Given a one-dimensional array, make all elements between 3 and 8 inclusive negative.

In [76]:
arr = np.array([1, 5, 6, 7, 8, 9, 2, 4, 3])

arr[(arr >= 3) & (arr <= 8)] *= -1

print(arr)

[ 1 -5 -6 -7 -8  9  2 -4 -3]


## Create a 5x5 matrix with row values ranging from 0 to 4

In [77]:
matrix = np.zeros((5, 5))
for i in range(5):
    matrix[i] = i
    
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


## Create a vector of size 12 with values ranging from 0 to 1, both excluded

In [78]:
vector = np.linspace(0, 1, num=12, endpoint=False)[1:]
print(vector)

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333 0.91666667]


## Create a random vector of size 10 and sort it

In [79]:
v = np.random.rand(10)

v_sorted = np.sort(v)

print(v_sorted)

[0.06622782 0.07823632 0.09714668 0.16315524 0.20991432 0.26694299
 0.46017871 0.71473755 0.73132529 0.96531487]


## Consider two random array A anb B, check if they are equal

In [80]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

if np.array_equal(A, B):
    print("A ve B dizileri birbirine eşittir.")
else:
    print("A ve B dizileri birbirine eşit değildir.")

A ve B dizileri birbirine eşit değildir.


## Create random vector of size 10 and replace the maximum value by 0

In [81]:
vektör = np.random.rand(10)

print("Orjinal vector:")
print(vektör)

max_index = np.argmax(vektör)

vektör[max_index] = 0

print("Modified vector:")
print(vektör)

Orjinal vector:
[0.04089984 0.08300418 0.26691068 0.44636948 0.67219326 0.78777109
 0.83343167 0.81615435 0.38753125 0.70577938]
Modified vector:
[0.04089984 0.08300418 0.26691068 0.44636948 0.67219326 0.78777109
 0.         0.81615435 0.38753125 0.70577938]


## How to swap two rows of an array?

In [82]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Orjinal array:")
print(arr)

arr[[0, 1], :] = arr[[1, 0], :]


print("last array:")
print(arr)


Orjinal array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
last array:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


## How to find the most frequent value in an array?

In [83]:
arr = np.random.randint(0, 10, size=20)

most_frequent_value = np.argmax(np.bincount(arr))

print("Dizideki en sık kullanılan değer:", most_frequent_value)


Dizideki en sık kullanılan değer: 7
